# Configuración de la aplicación
spring.application.name=wallpint

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/wallpint
spring.datasource.username=postgres
spring.datasource.password=3993
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (Mapeo Objeto-Relacional)
# 'update' actualiza el esquema de la BD automáticamente al arrancar
# 'create' borra y vuelve a crear el esquema cada vez
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola el código SQL que genera Hibernate (muy útil para depurar)
spring.jpa.show-sql=true

# Dialecto específico para aprovechar al máximo PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect